export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const CREATE_ORDER = 'CREATE_ORDER';
export const SHOW_ORDERS = 'SHOW_ORDERS';

export const FETCH_CHECKOUT_SUMMARY = 'FETCH_CHECKOUT_SUMMARY';


// export const ADD_INGREDIENT = 'ADD_INGREDIENT';
// export const ADD_INGREDIENT = 'ADD_INGREDIENT';
// export const ADD_INGREDIENT = 'ADD_INGREDIENT';
// export const ADD_INGREDIENT = 'ADD_INGREDIENT';